return {
	"github/copilot.vim",

	-- Chat extension for Copilot.
	{
		"CopilotC-Nvim/CopilotChat.nvim",
		dependencies = {
			{ "nvim-lua/plenary.nvim", branch = "master" },
		},
		-- Generated by Copilot :-)
		-- Required to compile the tiktoken library for efficient token counting used by the plugin.
		build = "make tiktoken",
	},
}
