#!/usr/bin/env bash

alias vim="nvim"
export EDITOR="nvim"
export VISUAL="nvim"

# Binds.

# Open tmux sessions with fuzzy finder.
bindkey -s '^t' '~/.config/bin/tmux-sessionizer\n'
# Open Zellij sessions with fuzzy finder.
# bindkey -s '^t' '~/.config/bin/zellij-sessionizer\n'
