[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/terminal/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/chrome/']
home=['<Super>e']
screensaver=@as []

[custom-keybindings/chrome]
binding='<Super>c'
command='google-chrome'
name='Chrome'

[custom-keybindings/terminal]
binding='<Super>Return'
command='/home/pedro.silva/.cargo/bin/alacritty'
name='Terminal'
