[/]
active-window-hint-color='rgb(211,70,21)'
auto-tile=@as []
last-version-installed=46
overridden-settings={'org.gnome.mutter.edge-tiling': <@mb nothing>}
single-screen-gap=8
tile-left-half=@as []
tile-right-half=@as []
window-gap=8
