[ids]
*

[main]
altgr = oneshot(alt)
alt = layer(nav)
ro = layer(shift) # Useless ABNT2 key on some laptops

[nav]
h = left
k = up
j = down
l = right
comma = home
. = end
backspace = delete
o = pageup
p = pagedown
