[ids]
# HHKB
04fe:0021:f26878c3
04fe:0021:52820c19
04fe:0021:38fc4e01
0fac:0ade:bea394c0
0fac:1ade:d2b36ae6

[main]
# Right Alt.
# leftalt = oneshot(meta)
leftalt = layer(meta) # hold
# Right Diamond.
# meta = oneshot(alt)
meta = layer(alt)
# Fix Alt Gr.
altgr = oneshot(alt)

# Navigation using Fn.
kpasterisk = left
kpslash = down
home = up
pageup = right
end = home
pagedown = end
numlock = delete
scrolllock = pageup
pause = pagedown
