import = ["~/.config/alacritty/theme.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500
unfocused_hollow = false
[cursor.style]
shape = "Block"
blinking = "Always"

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[font.glyph_offset]
x = 0
y = 0

[font]
# Iosevka font size.
# size = 11.9
# Comic font size.
size = 12.2 # or 12.3

[font.bold]
# family = "Iosevka Nerd Font Mono"
family = "ComicShannsMono Nerd Font Propo"
style = "Bold"

[font.italic]
# family = "Iosevka Nerd Font Mono"
family = "ComicShannsMono Nerd Font Propo"
style = "Italic"

[font.normal]
# family = "Iosevka Nerd Font Mono"
family = "ComicShannsMono Nerd Font Propo"
style = "Regular"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
opacity = 1.0

[window.padding]
x = 0
y = 0
